[package]
name = "integration-tests"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[dependencies]
lazy_static = "1"
reqwest = "0.9"

[build-dependencies]
rustc_version = "0.2"

[features]
default = []
test_wasm32_unknown_unknown = []
